import { NextRequest, NextResponse } from 'next/server'
import { XAIResponse } from '@/lib/xai-client'
import { storeLead } from '@/lib/database'
import { sendImplementationReport } from '@/lib/email-service'

export async function POST(request: NextRequest) {
  try {
    const { email, name, selectedProcesses, businessInfo } = await request.json()

    if (!email || !name || !selectedProcesses) {
      return NextResponse.json(
        { error: 'Missing required fields' },
        { status: 400 }
      )
    }

    // Generate detailed implementation plan using AI
    const implementationPlan = await generateImplementationPlan(
      selectedProcesses,
      businessInfo,
      name
    )

    // Store lead in database for follow-up
    const leadId = await storeLead({
      email,
      name,
      businessInfo,
      selectedProcesses: selectedProcesses.map((p: any) => ({
        id: p.id,
        name: p.name,
        rating: p.userRating
      })),
      reportGenerated: true,
      timestamp: new Date()
    })

    // Send email with implementation plan
    const emailSent = await sendImplementationReport(email, name, implementationPlan)

    console.log('Report generated and sent to:', email, 'Lead ID:', leadId)

    return NextResponse.json({
      success: true,
      message: 'Detailed implementation plan has been sent to your email',
      reportId: `report_${Date.now()}`,
      leadId,
      emailSent
    })

  } catch (error) {
    console.error('Error generating report:', error)
    return NextResponse.json(
      { error: 'Failed to generate report' },
      { status: 500 }
    )
  }
}

async function generateImplementationPlan(
  selectedProcesses: any[],
  businessInfo: string,
  name: string
): Promise<string> {
  // This would use your XAI client to generate a detailed implementation plan
  // For now, return a mock implementation plan
  
  const plan = `
# AI Implementation Plan for ${name}

## Business Overview
${businessInfo}

## Selected AI Solutions
${selectedProcesses.map((process: any) => `
### ${process.name}
- **Time Savings**: ${process.timeSavings} hours/week
- **Cost Savings**: ${process.costSavings}%
- **Revenue Impact**: +${process.revenueImpact}%
- **Implementation Timeline**: ${process.implementationTimeline}
- **Monthly Cost**: ${process.monthlyCost}
- **Setup Cost**: ${process.setupCost}
- **Expected ROI**: ${process.expectedROI}

**What This Means**: ${process.detailedDescription}

**Prerequisites**: ${process.prerequisites?.join(', ') || 'None specified'}

**Recommended Tools**: ${process.suggestedTools?.join(', ') || 'Custom solution recommended'}
`).join('\n')}

## Implementation Roadmap

### Phase 1: Foundation (Month 1)
- Set up basic infrastructure
- Begin data collection and analysis
- Start with highest-impact, lowest-complexity solution

### Phase 2: Core Implementation (Months 2-3)
- Deploy primary AI solutions
- Train staff on new systems
- Monitor and optimize performance

### Phase 3: Optimization (Months 4-6)
- Fine-tune AI models
- Expand to additional processes
- Measure ROI and adjust strategy

## Next Steps
1. Schedule a strategy call to discuss implementation details
2. Begin with your highest-priority process
3. Set up monthly check-ins to track progress

---
*Generated by Evergreen Web Solutions AI Assessment Tool*
*For questions, contact: info@evergreenwebsolutions.com*
  `

  return plan
}
